version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    env_file:
      - .env.production
    depends_on:
      - redis
      - worker
    networks:
      - app-network

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env.production
    networks:
      - app-network
    command: node src/worker

  redis:
    image: redis:alpine
    networks:
      - app-network

networks:
  app-network:
    external: true